#!/bin/sh
cd "${0%/*}" || exit                         # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions # Tutorial run functions


# 针对未关闭SIP的macOS操作系统的额外处理脚本
# Work-around for cleared PATH and DYLD_LIBRARY_PATH variables
isSIPEnabled()
{
    $(which -s csrutil) && {
    [ $(csrutil status | awk '{print $5}' | tr -d ".") = "enabled" ] \
        && return 0
    }
    return 1
}

[ "$(uname -s)" = "Darwin" ] && isSIPEnabled && . $WM_PROJECT_DIR/etc/bashrc
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication mapFields ../steady -sourceTime latestTime -consistent

runApplication decomposePar

runParallel $(getApplication)
